package dao;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;

import dao.mappers.IMapResultSetIntoEntity;
import dao.uow.IUnitOfWork;
import domain.model.Author;

public class AuthorRepository
        extends RepositoryBase<Author>
        implements IAuthorRepository{

    public AuthorRepository(Connection connection,
                            IMapResultSetIntoEntity<Author> mapper,
                            IUnitOfWork uow) {
        super(connection, mapper,uow);
    }

    @Override
    protected String tableName() {
        return "person";
    }

    @Override
    protected String createTableSql() {
        return "CREATE TABLE author("
                + "id bigint GENERATED BY DEFAULT AS IDENTITY,"
                + "name VARCHAR(20),"
                + "surname VARCHAR(50)"
                + ")";
    }

    @Override
    protected String insertSql() {
        return "INSERT INTO author(name,surname) VALUES(?,?)";
    }

    @Override
    protected String updateSql() {
        return "UPDATE author set name=?, surname=? WHERE id=?";
    }


    @Override
    protected void setupInsert(Author entity) throws SQLException {
        insert.setString(1, entity.getName());
        insert.setString(2, entity.getSurname());

    }

    @Override
    protected void setupUpdate(Author entity) throws SQLException {
        update.setString(1, entity.getName());
        update.setString(2, entity.getSurname());
        update.setInt(3, entity.getId());

    }

    public List<Author> withName(String name) {
        // TODO Auto-generated method stub
        return null;
    }


}
